
name: Security Scan

on:
  push:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  sca-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4
        continue-on-error: true

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.json
