name: Security Scan

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # SAST (Code scanning)
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v3

    # SCA (dependency check)
    - name: Dependency Review
      uses: actions/dependency-review-action@v3

    # SBOM
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        path: .
        format: cyclonedx-json
        output-file: sbom.json
